name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Init
        run: |
          terraform init
      - name: Initialize workspace
        run: |
          terraform workspace new dev || terraform workspace select dev     
      - name: Plan
        run: |
          terraform plan
      - name: Apply
        run: |
          terraform apply -auto-approve
